
name: Deploy Manual
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_IMAGE: keboola-component
      KBC_DEVELOPERPORTAL_USERNAME: ${{ secrets.KBC_DEVELOPERPORTAL_USERNAME }}
      KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ secrets.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_DEVELOPERPORTAL_APP: ${{ secrets.KBC_DEVELOPERPORTAL_APP }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Build image
      run: docker build -t component .

    - name: Push image
      uses: odinuv/action-push-to-ecr@master
      with:
        vendor: ${{ secrets.vendor }}
        app_id: ${{ secrets.app_id }}
        username: ${{ secrets.developer_portal_user }}
        password: ${{ secrets.developer_portal_password }}
        tag: ${{ github.ref }}
        push_latest: true
        source_image: component

    - name: Deploy to production
      uses: keboola/action-set-tag-developer-portal@master
      with:
        vendor: ${{ secrets.vendor }}
        app_id: ${{ secrets.app_id }}
        username: ${{ secrets.developer_portal_user }}
        password: ${{ secrets.developer_portal_password }}
        tag: ${{ github.ref }}
